version: "3"
services:
  api:
    build:
      context: .
      args:
        - ENV=development
        - PORT=4000
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:3000
    command: npm run dev
