version: "3"
services:
  db:
    container_name: db_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/data/db
  api:
    container_name: api_container
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  db:
