### GET All Users
GET http://localhost:3000/api/v1/users/users


### LOGIN
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "tarek2@gmail.com",
    "password": "12345678"
}


### REGISTER
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
    "name": "LOL",
    "email": "tarek@gmail.com",
    "password": "12345678"
}

### LOGOUT
POST http://localhost:3000/api/v1/users/logout
Content-Type: application/json

{
    "email": "test5@gmail.com"
}

### CREATE ROOM
POST http://localhost:3000/api/v1/room/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

{
    "name": "MML",
    "code": "123456789"
}


### GET ALL ROOM
GET http://localhost:3000/api/v1/room/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI


### GET MY ROOM
GET http://localhost:3000/api/v1/room/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI


### JOIN ROOM
PUT http://localhost:3000/api/v1/room/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5MTk0MTIxNn0.E-horYJN8tQlUSaSXFXJmw6W36SdSwoSIC5NGDaiBS8

{
    "code": "123456"
}

### UPDATE ROOM
PUT http://localhost:3000/api/v1/room/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

{
    "id": 19,
    "name": "updated name",
    "code": "updated code"
}


### ADD CATEGORY
POST http://localhost:3000/api/v1/food/food/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

{
    "name": "Syrian"
}


### ADD FOOD
POST http://localhost:3000/api/v1/food/food
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

{
    "name": "Mexicano with cheese",
    "price": 50,
    "restaurant": "Alawael",
    "category_id": 1
}

### ADD FOOD TO ROOM
POST http://localhost:3000/api/v1/food/food/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

{
    "food_id": "2",
    "room_id": "2"
}


### GET FOOD By User
GET http://localhost:3000/api/v1/food/food
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

### GET FOOD By Room
GET http://localhost:3000/api/v1/food/food/room/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI


### ADD ORDER
POST http://localhost:3000/api/v1/order/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI

{
    "food_id": "1",
    "room_id": "2",
    "quantity": 1
}


### GET ORDERS By ROOM
GET http://localhost:3000/api/v1/room/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI


### DELETE ORDERS By ROOM
DELETE http://localhost:3000/api/v1/room/delete/orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTk0MDEzMn0.UWULZw-8xIgEhGKPy7w0tq2DLQE05yaF5piPKkWD8OI
