### GET All Users
GET http://localhost:3000/api/v1/users/users


### LOGIN
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678"
}


### REGISTER
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
    "name": "LOL",
    "email": "test@gmail.com",
    "password": "12345678"
}

### LOGOUT
POST http://localhost:3000/api/v1/users/logout
Content-Type: application/json

{
    "email": "test5@gmail.com"
}

### CREATE ROOM
POST http://localhost:3000/api/v1/room/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5MTQzMTQ3M30.TMcsPcuA9aokBwD9FRQjMPFjz8oxBjZbARS_BropD84

{
    "name": "MML",
    "code": "123456789"
}


### GET ALL ROOM
GET http://localhost:3000/api/v1/room/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTQyODg4Nn0.nTu-BsqMzptce9RV7GRMQTCME85UR-6X8gZ_iSZvUbM


### GET MY ROOM
GET http://localhost:3000/api/v1/room/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5MTQzMTQ3M30.TMcsPcuA9aokBwD9FRQjMPFjz8oxBjZbARS_BropD84


### JOIN ROOM
PUT http://localhost:3000/api/v1/room/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MTQyODg4Nn0.nTu-BsqMzptce9RV7GRMQTCME85UR-6X8gZ_iSZvUbM

{
    "code": "123456789"
}

### UPDATE ROOM
PUT http://localhost:3000/api/v1/room/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5MDY5NjAzMH0.TrL6V3EyJh-cxvmGmzCQ9J_xLUux-Nd6YWdLhuYWrDw

{
    "id": 19,
    "name": "updated name",
    "code": "updated code"
}